#!/bin/bash
#
# Title:      Zerotier Installer
# Author(s):  Cuwia
# URL:        
# GNU:        General Public License v3.0
################################################################################
source /opt/plexguide/menu/functions/functions.sh

question1() {
  touch /var/plexguide/zt.network

  a7=$(cat /var/plexguide/zt.network)
  if [[ "$a7" != "good" ]]; then shieldcheck; fi
  echo good >/var/plexguide/auth.bypass

 
  domain=$(cat /var/plexguide/server.domain)

  tee <<-EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🛡️  PTS-ZeroTier 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
💬   Zerotier Must be installed prior from apps

[1] Set Network ID
[2] Setup IP
[3] Deploy ZT

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EOF
  phase1
}

phase1() {

  read -p 'Type a Number | Press [ENTER]: ' typed </dev/tty

  case $typed in
  1) netid && phase1 ;;
  2) setip && phase1 ;;
  3)
    # Sanity Check to Ensure Zertoier Installed
#    touch /var/plexguide/pgshield.emails
#    efg=$(cat "/var/plexguide/pgshield.emails")
#    if [[ "$efg" == "" ]]; then
#      echo
#      echo "SANITY CHECK: Zerotier is not installed! Exiting!"
#      read -p 'Acknowledge Info | Press [ENTER] ' typed </dev/tty
#      question1
#    fi

    # Sanity Check to Ensure Network ID Set
#    touch /var/plexguide/zerotier.ports
    touch /var/plexguide/ztNet.id
    ztnetid=$(cat "/var/plexguide/ztNet.id")
    if [ "$ztnetid" != "" ]; then
      echo
      echo "SANITY CHECK: Network ID is not set, PTS-ZeroTier cannot be enabled until this is set"
      read -p 'Acknowledge Info | Press [ENTER] ' typed </dev/tty
      question1
    fi


    # Sanity Check to Ensure Ip Set
    touch /var/plexguide/zt.ip
    ztip=$(cat "/var/plexguide/zt.ip")
    if [ "$ztip" != "" ]; then
      echo
      echo "SANITY CHECK: IP is not set, PTS-ZeroTier cannot be enabled until this is set"
      read -p 'Acknowledge Info | Press [ENTER] ' typed </dev/tty
      question1
    fi

  bash /opt/plexguide/menu/portguard/rebuild.sh
  z) exit ;;
  Z) exit ;;
  *) question1 ;;
  esac
}


netid() {
  tee <<-EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔑 Setup Zerotier - Network ID - IP
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Note :  Use the link for more information 

https://github.com/PTS-Team/PTS-Team/wiki/PTS-Zerotier

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EOF

  read -p '↘️  Network ID     | Press [Enter]: ' networkID </dev/tty
  if [ "$networkid" = "exit" ]; then question1; fi
  touch /opt/appdata/zerotier-one/var/networks.d/$networkid.conf
  echo $networkID > /var/plexguide/ztNet.id
    read -p '🔑 Network ID Set ZeroTier Docker will restart |  Press [ENTER] ' public </dev/tty
  question1

bash docker restart zerotier-one

}


setip() {

  tee <<-EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔑 Setup Zerotier - Set IP
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Note :  Use the link for more information 

https://github.com/PTS-Team/PTS-Team/wiki/PTS-Zerotier

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EOF

  read -p '↘️  IP Address     | Press [Enter]: ' ipadd </dev/tty
  if [ "$ipadd" = "exit" ]; then question1; fi
  echo $ipadd & ":" > /var/plexguide/zt.ip
  echo $ipadd & ":" >/var/plexguide/server.ports

  question1
}

